### PR TITLE
plt.close prevents opening figure with every resize

### PR DESCRIPTION
**Pull request by bigfooted**
Two small fixes to the matplotlib example.

1.
The matplotlib example 05_charts/Matplotlib/00_matplotlib-charts.py will replot the figure when you resize the window. When you resize it for a couple of seconds, you will get the message:
~/trame/examples/05_charts/Matplotlib/00_matplotlib-charts.py:45: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (matplotlib.pyplot.figure) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam figure.max_open_warning). Consider using matplotlib.pyplot.close(). fig, ax = plt.subplots(**figure_size())

I just placed a
plt.close('all')
before the fig,ax=plt.subplots() line and I did not get this message anymore. 

2. 
00_matplotlib-charts.py:118: UserWarning: color is redundantly defined by the 'color' keyword argument and the fmt string "--k" (-> color='k'). The keyword argument will take precedence.
  ax.plot(t, x, "--k", lw=3, color="blue")

I removed the "k" from the fmt string

see discussion on:  https://github.com/Kitware/trame/discussions/349

### CODE REVIEW

**Comment by jourdain** [comment]
Can you rename your commit to `docs(matplotlib): update examples to close the plots`

**Comment by jourdain** [comment]
And run `black  examples/05_charts/Matplotlib/00_matplotlib-charts.py`

**Comment by bigfooted** [comment]
Sorry, this PR was closed automatically when I force-pushed the reverted commit to change the commit message (then there was no change, should have added the new commit message first).

**Comment by jourdain** [comment]
I guess you just needed to do an `--amend` and force push. Now the PR is indeed empty (no commit)

**Pull request closed without merging**
